### ISSUE TITLE
[ISSUE] Windows Build Error - Secrets

### ISSUE THREAD

**Issue by CHE-11** [Liso-Vault/app#1]
Attempting build on Windows 10 Machine for Desktop App when ran into the error below. 

From command line:

```
Because liso depends on secrets from path which doesn't exist (could not find package secrets at "..\secrets"), version solving failed.
Running "flutter pub get" in app...                                     
pub get failed (66; Because liso depends on secrets from path which doesn't exist (could not find package secrets at       
"..\secrets"), version solving failed.)
```

**Comment by oliverbytes** [comment]
Hi @CHE-11, the **secrets** package is currently **ignored intentionally** because it contains secret keys. Right now, the status of Liso being open-source is just for self-auditing purposes only.
