### ISSUE TITLE
Android welcome page bug

### ISSUE THREAD

**Issue by M1n-4d316e** [Liso-Vault/app#6]
The welcome page buttons doesn't work, just the Terms of Use and Privacy Policy buttons.
Bug on my test device with 5.65" screen size.

![NexSnap-Oct-08-2022_02-30-58_PM](https://user-images.githubusercontent.com/54779580/194707803-814c04f7-7c7b-420a-9b6d-5dd5c700a113.png)

**Comment by oliverbytes** [comment]
This is now fixed in the next update! Thank you so much!
